export const SET_SEARCH_TERM        = 'SET_SEARCH_TERM';

export const REQUEST_ROBOTS_PENDING = 'REQUEST_ROBOTS_PENDING';

export const REQUEST_ROBOTS_SUCCESS = 'REQUEST_ROBOTS_SUCCESS';

export const REQUEST_ROBOTS_ERROR   = 'REQUEST_ROBOTS_ERROR';